### ISSUE TITLE
Exclude some device trackers

### ISSUE THREAD

**Issue by Twit123** [Sha-Darim/geo_address#3]
Hi,

Thanks for this component, it's working great.

I would like a way to exclude certain device trackers from geo_address. For example I have an ASUS router so this tracks when people are home or not but that's all so the address will never change so it seems pointless to show this and I would imagine the component will keep checking.

Possibly filter on "source_type: gps" as the ASUS has "source_type: router"

Thanks

Simon

**Comment by Sha-Darim** [comment]
Good idéa. I'll look into that :-)

**Comment by Sha-Darim** [comment]
New configuration option in place in latest push

**Comment by Twit123** [comment]
Hi,

Thanks for including this, it's works great.

You may want to add a note to the readme that the exclude_ids only accepts the entity name and not the entity type. 

Like in the readme, to exclude wilmer, I would add wilmer_wilmer to the exclude_ids field and NOT device_tracker.wilmer.wilmer. 

Took me a while to figure it out.

My config looks like this now:

```
geo_address:
  use_state: true
  use_timed: true  
  update_interval: 60
  update_period: 3600
  excluded_ids: brandon_arp brandons8 lyndasiphone lynn_arp sarah_arp sarahsiphone simon_arp simons_s8 someonesphone vickys_arp
```
Thanks

Simon

**Comment by Sha-Darim** [comment]
Thank you for your comment on this.

I'm currenty working to simplify the way the excluded ids are used in the code. I'll take a look at this as well. I could possibly add the ability to add the excluded devices with or without the entity_type.

**Comment by Sha-Darim** [comment]
OK, just pushed a new version. I hope this makes things a bit clearer :-)
I've adopted a more standarized way to handle includes and excludes.

**Comment by Twit123** [comment]
Hi,

That's perfect and both exclude and include work exactly as expected. 

My config looks like this now.

```
geo_address:
  use_state: true
  use_timed: true  
  update_interval: 60
  update_period: 3600
  include:
    entities:
      - device_tracker.life360_brandon
      - device_tracker.life360_lyn
      - device_tracker.life360_sarah
      - device_tracker.life360_simon
      - device_tracker.life360_terry
      - device_tracker.life360_vicky
```
Thanks

Simon
